### ISSUE TITLE
Defines as constants

### ISSUE THREAD

**Issue by StoneCypher** [ellowrath/ClangMan#7]
[Starting with line 10, in clangman.c](https://github.com/ellowrath/ClangMan/blob/dev/clangman.c#L10), you use `#define` to create constants.

Define for constants is generally a code smell.  Every place you use those constants you'll get a new copy of the information.  For a project this size that doesn't really matter, but, consider the defines in an API: they can be used tens or hundreds of thousands of times, and if they're strings, that might mean wasting hundreds of K in caches and fast code paths.  

In embedded, this can be a lot more serious; it can leave you with information which isn't where the `crt` expects constant data to go, leading to potentially slower accesses, higher memory costs, &c.

If instead it was a constant, it'd only have one copy, and it'd be a pointer being considered

**Comment by ellowrath** [comment]
Is it acceptable to keep [NAMESIZE](https://github.com/ellowrath/ClangMan/blob/dev/clangman.c#L10) as a `#define`? Changing it to a variable causes `variably modified array at file scope`. Since I use that value twice (to initialize the playerName, and as the second parameter in the fgets call) I'd like to have it set only once.

**Comment by StoneCypher** [comment]
You can do what you want, but the expected solution to that is to make it `static` so that it is no longer at file scope
